/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package formulaires;
import dao.CommandeDAO;
import dao.CrudResult;
import dao.ProduitDAO;
import entity.Commande;
import entity.LigneCommande;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import entity.Produit;
import java.util.HashMap;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import utilitaires.ApplicationColors;
/**
/**
 *
 * @author sevtify
 */
public class CommandesPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommandesPanel
     */
    public CommandesPanel() {
        initComponents();
        initCustomComponents();
    }
    
    private void initCustomComponents(){
        jspCartesProduits.getVerticalScrollBar().setUnitIncrement(16);
        CrudResult<List<Produit>> produits = ProduitDAO.getInstance().recupererTout();
        System.out.println(produits);
        produits.getDonnes().addAll(produits.getDonnes());
        produits.getDonnes().addAll(produits.getDonnes());
        afficherProduits(produits.getDonnes());
    }
    private void afficherProduits(List<Produit> produits) {
        jpCartesProduits.removeAll();


        for (Produit p : produits) {
            ProductCard card = new ProductCard(
                p.getNom(), 
                p.getCategorie().getLIBELLE(), 
                p.getPrixDeVente()+ " FCFA", 
                p.getStockActuel(),
                p.getSeuilAlerte()
            );
            jpCartesProduits.add(card);
        }

        jpCartesProduits.revalidate();
        jpCartesProduits.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTopbarCommandes = new javax.swing.JPanel();
        jlLabelDuPanneau = new javax.swing.JLabel();
        jbAncienneCommande = new javax.swing.JButton();
        jpContenuPrincipalCommandes = new javax.swing.JPanel();
        jpConteneurCatalogueProduit = new javax.swing.JPanel();
        jpCatalogueProduit = new javax.swing.JPanel();
        jpTitreCatalogue = new javax.swing.JPanel();
        jlProduitsDispo = new javax.swing.JLabel();
        jpRechercheProduit = new javax.swing.JPanel();
        jtfRechercheProduit = new javax.swing.JTextField();
        jlLogoRecherche = new javax.swing.JLabel();
        jpConteneurCartesProduits = new javax.swing.JPanel();
        jspCartesProduits = new javax.swing.JScrollPane();
        jpCartesProduits = new javax.swing.JPanel();
        jpConteneurCommandeEnCours = new javax.swing.JPanel();
        jpCommandeEnCours = new javax.swing.JPanel();

        setBackground(ApplicationColors.BACKGROUND);
        setLayout(new java.awt.BorderLayout());

        jpTopbarCommandes.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 10, 10, 10));
        jpTopbarCommandes.setLayout(new java.awt.BorderLayout(50, 0));

        jlLabelDuPanneau.setBackground(ApplicationColors.BACKGROUND
        );
        jlLabelDuPanneau.setFont(new Font("Segoe UI", Font.BOLD, 20));
        jlLabelDuPanneau.setForeground(ApplicationColors.TEXT_PRIMARY);
        jlLabelDuPanneau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLabelDuPanneau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store.png"))); // NOI18N
        jlLabelDuPanneau.setText("Pannel Des Commandes");
        jpTopbarCommandes.add(jlLabelDuPanneau, java.awt.BorderLayout.CENTER);

        jbAncienneCommande.setBackground(ApplicationColors.SUCCESS);
        jbAncienneCommande.setFont(new Font("Segoe UI", Font.BOLD, 20));
        jbAncienneCommande.setForeground(ApplicationColors.TEXT_LIGHT);
        jbAncienneCommande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circle-arrow-right-light-l.png"))); // NOI18N
        jbAncienneCommande.setText("Continuer Une Ancienne Commande");
        jbAncienneCommande.setFocusPainted(false);
        jpTopbarCommandes.add(jbAncienneCommande, java.awt.BorderLayout.EAST);

        add(jpTopbarCommandes, java.awt.BorderLayout.NORTH);

        jpContenuPrincipalCommandes.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 10, 10, 10));
        jpContenuPrincipalCommandes.setLayout(new java.awt.GridLayout(1, 2, 25, 0));

        jpConteneurCatalogueProduit.setLayout(new java.awt.BorderLayout(25, 25));

        jpCatalogueProduit.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 25, 25, 25));
        jpCatalogueProduit.setLayout(new javax.swing.BoxLayout(jpCatalogueProduit, javax.swing.BoxLayout.Y_AXIS));

        jpTitreCatalogue.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        jpTitreCatalogue.setPreferredSize(new java.awt.Dimension(638, 100));
        jpTitreCatalogue.setLayout(new java.awt.BorderLayout());

        jlProduitsDispo.setBackground(ApplicationColors.PANEL_BG);
        jlProduitsDispo.setFont(new Font("Segoe UI", Font.BOLD, 20));
        jlProduitsDispo.setForeground(ApplicationColors.TEXT_PRIMARY);
        jlProduitsDispo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlProduitsDispo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stock.png"))); // NOI18N
        jlProduitsDispo.setText("Produit Disponibles");
        jlProduitsDispo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        jpTitreCatalogue.add(jlProduitsDispo, java.awt.BorderLayout.CENTER);

        jpCatalogueProduit.add(jpTitreCatalogue);

        jpRechercheProduit.setBorder(javax.swing.BorderFactory.createLineBorder(ApplicationColors.BORDER));
        jpRechercheProduit.setOpaque(false);
        jpRechercheProduit.setPreferredSize(new java.awt.Dimension(638, 100));
        jpRechercheProduit.setLayout(new java.awt.BorderLayout(20, 0));

        jtfRechercheProduit.setBackground(ApplicationColors.PANEL_BG);
        jtfRechercheProduit.setFont(new Font("Segoe UI", Font.PLAIN, 25));
        jtfRechercheProduit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfRechercheProduit.setBorder(javax.swing.BorderFactory.createLineBorder(ApplicationColors.BORDER));
        jtfRechercheProduit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jpRechercheProduit.add(jtfRechercheProduit, java.awt.BorderLayout.CENTER);

        jlLogoRecherche.setBackground(ApplicationColors.PANEL_BG);
        jlLogoRecherche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLogoRecherche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-xl.png"))); // NOI18N
        jpRechercheProduit.add(jlLogoRecherche, java.awt.BorderLayout.WEST);

        jpCatalogueProduit.add(jpRechercheProduit);

        jpConteneurCartesProduits.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 1, 1));
        jpConteneurCartesProduits.setPreferredSize(new java.awt.Dimension(638, 1000));
        jpConteneurCartesProduits.setLayout(new java.awt.BorderLayout());

        jpCartesProduits.setLayout(new java.awt.GridLayout(0, 3));
        jspCartesProduits.setViewportView(jpCartesProduits);

        jpConteneurCartesProduits.add(jspCartesProduits, java.awt.BorderLayout.CENTER);

        jpCatalogueProduit.add(jpConteneurCartesProduits);

        jpConteneurCatalogueProduit.add(jpCatalogueProduit, java.awt.BorderLayout.CENTER);

        jpContenuPrincipalCommandes.add(jpConteneurCatalogueProduit);

        jpConteneurCommandeEnCours.setLayout(new java.awt.BorderLayout(25, 25));

        jpCommandeEnCours.setLayout(new javax.swing.BoxLayout(jpCommandeEnCours, javax.swing.BoxLayout.Y_AXIS));
        jpConteneurCommandeEnCours.add(jpCommandeEnCours, java.awt.BorderLayout.CENTER);

        jpContenuPrincipalCommandes.add(jpConteneurCommandeEnCours);

        add(jpContenuPrincipalCommandes, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAncienneCommande;
    private javax.swing.JLabel jlLabelDuPanneau;
    private javax.swing.JLabel jlLogoRecherche;
    private javax.swing.JLabel jlProduitsDispo;
    private javax.swing.JPanel jpCartesProduits;
    private javax.swing.JPanel jpCatalogueProduit;
    private javax.swing.JPanel jpCommandeEnCours;
    private javax.swing.JPanel jpConteneurCartesProduits;
    private javax.swing.JPanel jpConteneurCatalogueProduit;
    private javax.swing.JPanel jpConteneurCommandeEnCours;
    private javax.swing.JPanel jpContenuPrincipalCommandes;
    private javax.swing.JPanel jpRechercheProduit;
    private javax.swing.JPanel jpTitreCatalogue;
    private javax.swing.JPanel jpTopbarCommandes;
    private javax.swing.JScrollPane jspCartesProduits;
    private javax.swing.JTextField jtfRechercheProduit;
    // End of variables declaration//GEN-END:variables
}
