/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package formulaires;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import utilitaires.ApplicationColors;
/**
 *
 * @author sevtify
 */
public class DashBoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashBoardPanel
     */
    public DashBoardPanel() {
        initComponents();
        initCustomCOmponents();
    }
    
    private void initCustomCOmponents(){
        rafraichirListeCommandes(jPanel24);
        rafraichirListeCommandes(jPanel20);
    }
    
    public static void main(String[] args) {
         java.awt.EventQueue.invokeLater(() -> new DashBoardPanel().setVisible(true));
    }
    
    private void rafraichirListeCommandes(JPanel containerParent) {
    containerParent.removeAll(); // Vide le contenu actuel
    
    // Exemple avec une boucle
        for (int i = 0; i < 5; i++) {
            JPanel card = createCard("Commande #" + "24", 
                                     "2x Burger, 1x Coca", 
                                     "1200" + " €");

            containerParent.add(card);
            containerParent.add(Box.createRigidArea(new Dimension(0, 10))); // Espacement entre cartes
                        
        }
    
    containerParent.revalidate(); // Indique à Swing de recalculer l'affichage
    containerParent.repaint();    // Force le redessin
}
    
    public JPanel createCard(String title, String subtitle, String amountOrValue) {
        // 1. Panel conteneur avec un layout propre
        JPanel card = new JPanel(new BorderLayout());
        card.setBackground(Color.WHITE);
        // Bordure fine pour l'effet carte
        card.setBorder(BorderFactory.createCompoundBorder(
            new LineBorder(new Color(230, 230, 230), 1, true),
            new EmptyBorder(15, 15, 15, 15)
        ));

        // 2. Panel pour le texte (gauche)
        JPanel textPanel = new JPanel(new GridLayout(2, 1));
        textPanel.setOpaque(false);

        JLabel lblTitle = new JLabel(title);
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 16));

        JLabel lblSubtitle = new JLabel(subtitle);
        lblSubtitle.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblSubtitle.setForeground(Color.GRAY);

        textPanel.add(lblTitle);
        textPanel.add(lblSubtitle);

        // 3. Label pour le montant/valeur (droite)
        JLabel lblAmount = new JLabel(amountOrValue);
        lblAmount.setFont(new Font("Segoe UI", Font.BOLD, 16));
        lblAmount.setForeground(new Color(33, 150, 243)); // Couleur primaire

        card.add(textPanel, BorderLayout.CENTER);
        card.add(lblAmount, BorderLayout.EAST);

    return card;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCartes = new javax.swing.JPanel();
        jpCarte1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpCarte5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpCarte6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jpCarte7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jpNavigation = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jpDetailsDashorad = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jpCartes.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        jpCarte1.setBackground(ApplicationColors.BACKGROUND);
        jpCarte1.setBorder(new javax.swing.border.MatteBorder(null));
        jpCarte1.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel1.setBackground(ApplicationColors.PANEL_BG);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(ApplicationColors.BACKGROUND);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/in-stock (1).png"))); // NOI18N
        jPanel3.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jpCarte1.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setBackground(ApplicationColors.BACKGROUND);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 32));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("48");
        jPanel2.add(jLabel1);

        jLabel2.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        jLabel2.setForeground(ApplicationColors.TEXT_SECONDARY);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total Produits");
        jPanel2.add(jLabel2);

        jpCarte1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jpCartes.add(jpCarte1);

        jpCarte5.setBorder(new javax.swing.border.MatteBorder(null));
        jpCarte5.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel4.setBackground(ApplicationColors.PANEL_BG);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setBackground(ApplicationColors.BACKGROUND);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/purchase-order.png"))); // NOI18N
        jPanel5.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5);

        jpCarte5.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel6.setBackground(ApplicationColors.BACKGROUND);
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jLabel3.setFont(new Font("Segoe UI", Font.BOLD, 32));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("48");
        jPanel6.add(jLabel3);

        jLabel6.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        jLabel6.setForeground(ApplicationColors.TEXT_SECONDARY);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total Produits");
        jPanel6.add(jLabel6);

        jpCarte5.add(jPanel6, java.awt.BorderLayout.CENTER);

        jpCartes.add(jpCarte5);

        jpCarte6.setBorder(new javax.swing.border.MatteBorder(null));
        jpCarte6.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel7.setBackground(ApplicationColors.PANEL_BG);
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel7.setBackground(ApplicationColors.BACKGROUND);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money-bag.png"))); // NOI18N
        jPanel8.add(jLabel7, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8);

        jpCarte6.add(jPanel7, java.awt.BorderLayout.WEST);

        jPanel9.setBackground(ApplicationColors.BACKGROUND);
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jLabel8.setFont(new Font("Segoe UI", Font.BOLD, 32));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("48");
        jPanel9.add(jLabel8);

        jLabel9.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        jLabel9.setForeground(ApplicationColors.TEXT_SECONDARY);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total Produits");
        jPanel9.add(jLabel9);

        jpCarte6.add(jPanel9, java.awt.BorderLayout.CENTER);

        jpCartes.add(jpCarte6);

        jpCarte7.setBorder(new javax.swing.border.MatteBorder(null));
        jpCarte7.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel10.setBackground(ApplicationColors.PANEL_BG);
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel10.setBackground(ApplicationColors.BACKGROUND);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/danger.png"))); // NOI18N
        jPanel11.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel11);

        jpCarte7.add(jPanel10, java.awt.BorderLayout.WEST);

        jPanel12.setBackground(ApplicationColors.BACKGROUND);
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));

        jLabel11.setFont(new Font("Segoe UI", Font.BOLD, 32));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("48");
        jPanel12.add(jLabel11);

        jLabel12.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        jLabel12.setForeground(ApplicationColors.TEXT_SECONDARY);
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Total Produits");
        jPanel12.add(jLabel12);

        jpCarte7.add(jPanel12, java.awt.BorderLayout.CENTER);

        jpCartes.add(jpCarte7);

        add(jpCartes, java.awt.BorderLayout.NORTH);

        jpNavigation.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel13.setFont(new Font("Segoe UI", Font.BOLD, 25)
        );
        jLabel13.setForeground(ApplicationColors.TEXT_PRIMARY);
        jLabel13.setText("Navigation Rapide");
        jPanel14.add(jLabel13, java.awt.BorderLayout.CENTER);

        jpNavigation.add(jPanel14, java.awt.BorderLayout.NORTH);

        jPanel13.setLayout(new java.awt.GridLayout(1, 4, 25, 0));

        jPanel15.setBackground(ApplicationColors.BACKGROUND);
        jPanel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/store.png"))); // NOI18N
        jPanel15.add(jLabel14, java.awt.BorderLayout.NORTH);

        jLabel15.setFont(new Font("Segoe UI", Font.PLAIN, 22));
        jLabel15.setForeground(ApplicationColors.TEXT_PRIMARY);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Produits");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel15.add(jLabel15, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel15);

        jPanel16.setBackground(ApplicationColors.BACKGROUND);
        jPanel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.setLayout(new java.awt.BorderLayout(0, 24));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stock.png"))); // NOI18N
        jPanel16.add(jLabel16, java.awt.BorderLayout.NORTH);

        jLabel17.setFont(new Font("Segoe UI", Font.PLAIN, 22));
        jLabel17.setForeground(ApplicationColors.TEXT_PRIMARY);
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Stock");
        jPanel16.add(jLabel17, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel16);

        jPanel17.setBackground(ApplicationColors.BACKGROUND);
        jPanel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel17.setLayout(new java.awt.BorderLayout(0, 24));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping.png"))); // NOI18N
        jPanel17.add(jLabel18, java.awt.BorderLayout.NORTH);

        jLabel19.setFont(new Font("Segoe UI", Font.PLAIN, 22));
        jLabel19.setForeground(ApplicationColors.TEXT_PRIMARY);
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Commandes");
        jPanel17.add(jLabel19, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel17);

        jPanel18.setBackground(ApplicationColors.BACKGROUND);
        jPanel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel18.setLayout(new java.awt.BorderLayout(0, 24));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stats.png"))); // NOI18N
        jPanel18.add(jLabel20, java.awt.BorderLayout.NORTH);

        jLabel21.setFont(new Font("Segoe UI", Font.PLAIN, 22));
        jLabel21.setForeground(ApplicationColors.TEXT_PRIMARY);
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Statistiques");
        jPanel18.add(jLabel21, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel18);

        jpNavigation.add(jPanel13, java.awt.BorderLayout.CENTER);

        add(jpNavigation, java.awt.BorderLayout.CENTER);

        jpDetailsDashorad.setLayout(new java.awt.GridLayout(1, 2, 30, 0));

        jPanel19.setBackground(ApplicationColors.BACKGROUND);
        jPanel19.setLayout(new java.awt.BorderLayout(0, 15));

        jPanel21.setBackground(ApplicationColors.BACKGROUND);
        jPanel21.setLayout(new java.awt.BorderLayout());

        jLabel22.setBackground(ApplicationColors.BACKGROUND        );
        jLabel22.setFont(new Font("Segoe UI", Font.BOLD, 22));
        jLabel22.setForeground(ApplicationColors.TEXT_PRIMARY);
        jLabel22.setText("Produit en alertes de stock");
        jPanel21.add(jLabel22, java.awt.BorderLayout.CENTER);

        jPanel19.add(jPanel21, java.awt.BorderLayout.NORTH);

        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.Y_AXIS));
        jPanel19.add(jPanel20, java.awt.BorderLayout.CENTER);

        jpDetailsDashorad.add(jPanel19);

        jPanel22.setBackground(ApplicationColors.BACKGROUND);
        jPanel22.setLayout(new java.awt.BorderLayout(0, 15));

        jPanel23.setBackground(ApplicationColors.BACKGROUND);
        jPanel23.setLayout(new java.awt.BorderLayout());

        jLabel23.setBackground(ApplicationColors.BACKGROUND        );
        jLabel23.setFont(new Font("Segoe UI", Font.BOLD, 22));
        jLabel23.setForeground(ApplicationColors.TEXT_PRIMARY);
        jLabel23.setText("Dernières Commandes");
        jPanel23.add(jLabel23, java.awt.BorderLayout.CENTER);

        jPanel22.add(jPanel23, java.awt.BorderLayout.NORTH);

        jPanel24.setLayout(new javax.swing.BoxLayout(jPanel24, javax.swing.BoxLayout.Y_AXIS));
        jPanel22.add(jPanel24, java.awt.BorderLayout.CENTER);

        jpDetailsDashorad.add(jPanel22);

        add(jpDetailsDashorad, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jpCarte1;
    private javax.swing.JPanel jpCarte5;
    private javax.swing.JPanel jpCarte6;
    private javax.swing.JPanel jpCarte7;
    private javax.swing.JPanel jpCartes;
    private javax.swing.JPanel jpDetailsDashorad;
    private javax.swing.JPanel jpNavigation;
    // End of variables declaration//GEN-END:variables
}
