/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulaires;

import dao.AuditDAO;
import dao.CrudResult;
import dao.UsersDAO;
import entity.Audit;
import entity.Users;
import entity.enums.ActionType;
import java.awt.Component;
import java.time.Instant;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import utilitaires.AuthentificationManager;
import utilitaires.Security;

/**
 *
 * @author sevtify
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        
        FormsUtils.configurationDeBaseDeFenetre(this, FormsUtils.LOGIN_WIDTH, FormsUtils.LOGIN_HEIGHT);
        
        DocumentListener ecouteur = new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) { verifier(); }
            @Override
            public void removeUpdate(DocumentEvent e) { verifier(); }
            @Override
            public void insertUpdate(DocumentEvent e) { verifier(); }

            private void verifier() {
                
                // Un tout petit peu d'algo hihihihihi
                boolean pffff = jtfLogin.getText().trim().isEmpty()
                               ||
                               (String.copyValueOf(jpfMotDePasse.getPassword()).trim().isEmpty());
                
                jbConnexion.setEnabled(!pffff);
            }
        };
        
        jtfLogin.getDocument().addDocumentListener(ecouteur);
        jpfMotDePasse.getDocument().addDocumentListener(ecouteur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlLabelMDP2 = new javax.swing.JLabel();
        jlTitreResto = new javax.swing.JLabel();
        jlLabelMDP1 = new javax.swing.JLabel();
        jlMdpPhoto = new javax.swing.JLabel();
        jlUserPhoto = new javax.swing.JLabel();
        jpfMotDePasse = new javax.swing.JPasswordField();
        jtfLogin = new javax.swing.JTextField();
        jlLogo = new javax.swing.JLabel();
        jbConnexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ecran De Connexion");
        setBackground(utilitaires.ApplicationColors.PANEL_BG);
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);

        jlLabelMDP2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jlLabelMDP2.setText("Login");

        jlTitreResto.setBackground(utilitaires.ApplicationColors.BACKGROUND);
        jlTitreResto.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jlTitreResto.setForeground(utilitaires.ApplicationColors.TEXT_PRIMARY);
        jlTitreResto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitreResto.setText("Restaurant Chez Maman Rose");

        jlLabelMDP1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jlLabelMDP1.setText("Mot de Passe");

        jlMdpPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMdpPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock-keyhole.png"))); // NOI18N

        jlUserPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlUserPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jlUserPhoto.setToolTipText("");

        jpfMotDePasse.setBackground(utilitaires.ApplicationColors.BACKGROUND);
        jpfMotDePasse.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jpfMotDePasse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpfMotDePasse.setActionCommand("<Not Set>");
        jpfMotDePasse.addActionListener(this::jpfMotDePasseActionPerformed);

        jtfLogin.setBackground(utilitaires.ApplicationColors.BACKGROUND);
        jtfLogin.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jtfLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfLogin.addActionListener(this::jtfLoginActionPerformed);

        jlLogo.setBackground(utilitaires.ApplicationColors.PRIMARY);
        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fast-food.png"))); // NOI18N
        jlLogo.setText("");
        jlLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlLogo.setAlignmentX(0.5F);
        jlLogo.setAlignmentX(Component.CENTER_ALIGNMENT);

        jbConnexion.setBackground(utilitaires.ApplicationColors.PRIMARY
        );
        jbConnexion.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jbConnexion.setForeground(utilitaires.ApplicationColors.BACKGROUND
        );
        jbConnexion.setEnabled(false);
        jbConnexion.setLabel("Se Connecter");
        jbConnexion.addActionListener(this::jbConnexionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlTitreResto)
                        .addGap(115, 115, 115))))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlMdpPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlLabelMDP1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jpfMotDePasse)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlUserPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlLabelMDP2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jtfLogin))))
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 34, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLogo)
                .addGap(27, 27, 27)
                .addComponent(jlTitreResto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlLabelMDP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUserPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jlLabelMDP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlMdpPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpfMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jbConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jbConnexion.getAccessibleContext().setAccessibleDescription("");
        jbConnexion.setAlignmentX(Component.CENTER_ALIGNMENT);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConnexionActionPerformed
        String loginSaisi = jtfLogin.getText();
        char[] mdpSaisi = jpfMotDePasse.getPassword();
        
        String mdpString = String.copyValueOf(mdpSaisi);
        
        String mdpHash = Security.crypterMotdePasse(mdpString);
        
        CrudResult<Users> requeteRecupUtilisateur = UsersDAO.getInstance().seConnecter(loginSaisi, mdpHash);
        
        if (requeteRecupUtilisateur.estUnSucces()) {
            App.getInstance().lancerMenuPrincipal(requeteRecupUtilisateur.getDonnes());
        }else{
            AuthentificationManager.getInstance().enregistrerActionDansAuditSansUtilisateur(ActionType.MODIFICATION, "Tentative de connexion échouée avec les identifiants " + loginSaisi + " et "+ mdpString);
            jtfLogin.setText("");
            jpfMotDePasse.setText("");
            JOptionPane.showMessageDialog(rootPane, requeteRecupUtilisateur.getErreur(), "Erreur", JOptionPane.ERROR_MESSAGE);
            jtfLogin.requestFocus();
        }
        
        
        
    }//GEN-LAST:event_jbConnexionActionPerformed

    private void jtfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfLoginActionPerformed

    private void jpfMotDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfMotDePasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfMotDePasseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbConnexion;
    private javax.swing.JLabel jlLabelMDP1;
    private javax.swing.JLabel jlLabelMDP2;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlMdpPhoto;
    private javax.swing.JLabel jlTitreResto;
    private javax.swing.JLabel jlUserPhoto;
    private javax.swing.JPasswordField jpfMotDePasse;
    private javax.swing.JTextField jtfLogin;
    // End of variables declaration//GEN-END:variables
}
