/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package formulaires;

import entity.Users;

/**
 *
 * @author loyale
 */
public class ModifierUser extends javax.swing.JDialog {

    
    
    private void effacerChamps() {
    // Vide les champs texte
    T_login.setText("");
    T_passe.setText("");
    
    // Remet les sélections par défaut (Sexe M et Admin Non)
    R_m.setSelected(true);
    R_non.setSelected(true);
    
    // Repositionne le curseur sur le champ Login
    T_login.requestFocus();
}
    
    private int idUser;
    public void preRemplir(int id, String login, String sexe, String role) {

    idUser = id;

    T_login.setText(login);

    // Sexe
    if ("F".equalsIgnoreCase(sexe)) {
        R_f.setSelected(true);
    } else {
        R_m.setSelected(true);
    }

    // Rôle
    if ("Admin".equalsIgnoreCase(role)) {
        R_oui.setSelected(true);
    } else {
        R_non.setSelected(true);
    }
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ModifierUser.class.getName());

    /**
     * Creates new form Modifi
     */
    public ModifierUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_sexe = new javax.swing.ButtonGroup();
        BG_isAdmin = new javax.swing.ButtonGroup();
        Titre = new javax.swing.JLabel();
        zone = new javax.swing.JPanel();
        L_login = new javax.swing.JLabel();
        L_passe = new javax.swing.JLabel();
        L_sexe = new javax.swing.JLabel();
        L_isAdmin = new javax.swing.JLabel();
        T_login = new javax.swing.JTextField();
        T_passe = new javax.swing.JTextField();
        R_f = new javax.swing.JRadioButton();
        R_m = new javax.swing.JRadioButton();
        R_oui = new javax.swing.JRadioButton();
        R_non = new javax.swing.JRadioButton();
        B_modifier = new javax.swing.JButton();
        B_annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Titre.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 18)); // NOI18N
        Titre.setText("Modification d'un Utilisateur");

        zone.setBorder(new javax.swing.border.MatteBorder(null));

        L_login.setText("Login : ");

        L_passe.setText("Mot de passe : ");

        L_sexe.setText("Sexe : ");

        L_isAdmin.setText("IS ADMIN ?");

        BG_sexe.add(R_f);
        R_f.setText("F");

        BG_sexe.add(R_m);
        R_m.setText("M");

        BG_isAdmin.add(R_oui);
        R_oui.setText("Oui");

        BG_isAdmin.add(R_non);
        R_non.setText("Non");

        javax.swing.GroupLayout zoneLayout = new javax.swing.GroupLayout(zone);
        zone.setLayout(zoneLayout);
        zoneLayout.setHorizontalGroup(
            zoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(zoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_login)
                    .addComponent(L_passe)
                    .addComponent(L_sexe)
                    .addComponent(L_isAdmin))
                .addGap(105, 105, 105)
                .addGroup(zoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(zoneLayout.createSequentialGroup()
                        .addComponent(R_oui)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(R_non))
                    .addGroup(zoneLayout.createSequentialGroup()
                        .addComponent(R_f)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(R_m))
                    .addGroup(zoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(T_login)
                        .addComponent(T_passe, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        zoneLayout.setVerticalGroup(
            zoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zoneLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(zoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(L_login)
                    .addComponent(T_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(zoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_passe)
                    .addComponent(T_passe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(zoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_sexe)
                    .addComponent(R_f)
                    .addComponent(R_m))
                .addGap(42, 42, 42)
                .addGroup(zoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(L_isAdmin)
                    .addGroup(zoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(R_oui)
                        .addComponent(R_non)))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        B_modifier.setBackground(new java.awt.Color(51, 255, 51));
        B_modifier.setForeground(new java.awt.Color(255, 255, 255));
        B_modifier.setText("Modifier");
        B_modifier.addActionListener(this::B_modifierActionPerformed);

        B_annuler.setBackground(new java.awt.Color(255, 51, 51));
        B_annuler.setForeground(new java.awt.Color(255, 255, 255));
        B_annuler.setText("Annuler");
        B_annuler.addActionListener(this::B_annulerActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B_modifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B_annuler)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titre)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Titre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_modifier)
                    .addComponent(B_annuler))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_annulerActionPerformed
        effacerChamps();
        this.dispose();
    }//GEN-LAST:event_B_annulerActionPerformed

    private void B_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_modifierActionPerformed
    Users user = new Users();
    user.setIdUser(idUser);
    user.setLogin(T_login.getText());
    user.setSexe(R_f.isSelected() ? "F" : "M");
    user.setIsAdmin(R_oui.isSelected());

    // Si le champ mot de passe est vide, on garde l'ancien depuis la BD
    String nouveauPasse = T_passe.getText().trim();
    if (nouveauPasse.isEmpty()) {
        // Récupérer l'ancien mot de passe
        dao.CrudResult<Users> ancienUser = 
            dao.UsersDAO.getInstance().lire(idUser);
        
        if (ancienUser.estUneErreur()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Impossible de récupérer l'ancien mot de passe");
            return;
        }
        user.setMotDePasse(ancienUser.getDonnes().getMotDePasse());
    } else {
        user.setMotDePasse(nouveauPasse);
    }

    try {
        dao.CrudResult<Users> result = 
            dao.UsersDAO.getInstance().mettreAJour(user);
        if (result.estUnSucces()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Utilisateur modifié avec succès !");
            dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                result.getErreur());
        }
    } catch (java.awt.HeadlessException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
    }

    }//GEN-LAST:event_B_modifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ModifierUser dialog = new ModifierUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BG_isAdmin;
    private javax.swing.ButtonGroup BG_sexe;
    private javax.swing.JButton B_annuler;
    private javax.swing.JButton B_modifier;
    private javax.swing.JLabel L_isAdmin;
    private javax.swing.JLabel L_login;
    private javax.swing.JLabel L_passe;
    private javax.swing.JLabel L_sexe;
    private javax.swing.JRadioButton R_f;
    private javax.swing.JRadioButton R_m;
    private javax.swing.JRadioButton R_non;
    private javax.swing.JRadioButton R_oui;
    private javax.swing.JTextField T_login;
    private javax.swing.JTextField T_passe;
    private javax.swing.JLabel Titre;
    private javax.swing.JPanel zone;
    // End of variables declaration//GEN-END:variables
}
