/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package formulaires;

import dao.CrudResult;
import java.awt.HeadlessException;
import utilitaires.Security;

/**
 *
 * @author loyale
 */
public class UserForm extends javax.swing.JDialog {
    private void effacerChamps() {
    // Vide les champs texte
    login.setText("");
    T_pass.setText("");
    
    // Remet les sélections par défaut (Sexe M et Admin Non)
    C_m.setSelected(true);
    non.setSelected(true);
    
    // Repositionne le curseur sur le champ Login
    login.requestFocus();
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserForm.class.getName());

    /**
     * Creates new form UserForm
     * @param parent
     * @param modal
     */
    public UserForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_sexe = new javax.swing.ButtonGroup();
        BG_isadmin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        L_login = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        passe = new javax.swing.JLabel();
        sexe = new javax.swing.JLabel();
        L_isAdminn = new javax.swing.JLabel();
        T_pass = new javax.swing.JTextField();
        C_f = new javax.swing.JRadioButton();
        C_m = new javax.swing.JRadioButton();
        oui = new javax.swing.JRadioButton();
        non = new javax.swing.JRadioButton();
        enregistrer = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();
        Titre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        L_login.setText("Login : ");

        passe.setText("Mot de passe : ");

        sexe.setText("Sexe : ");

        L_isAdminn.setText("IS ADMIN ?");

        BG_sexe.add(C_f);
        C_f.setSelected(true);
        C_f.setText("F");

        BG_sexe.add(C_m);
        C_m.setText("M");

        BG_isadmin.add(oui);
        oui.setText("Oui");

        BG_isadmin.add(non);
        non.setSelected(true);
        non.setText("Non");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_login)
                    .addComponent(passe)
                    .addComponent(sexe)
                    .addComponent(L_isAdminn))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(oui)
                        .addGap(18, 18, 18)
                        .addComponent(non))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(C_f)
                        .addGap(18, 18, 18)
                        .addComponent(C_m))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(login)
                        .addComponent(T_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(L_login)
                            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(passe))
                    .addComponent(T_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexe)
                    .addComponent(C_f)
                    .addComponent(C_m))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_isAdminn)
                    .addComponent(oui)
                    .addComponent(non))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        enregistrer.setBackground(new java.awt.Color(102, 255, 102));
        enregistrer.setForeground(new java.awt.Color(255, 255, 255));
        enregistrer.setText("Enregistrer");
        enregistrer.addActionListener(this::enregistrerActionPerformed);

        Annuler.setBackground(new java.awt.Color(255, 51, 51));
        Annuler.setForeground(new java.awt.Color(255, 255, 255));
        Annuler.setText("Annuler");
        Annuler.addActionListener(this::AnnulerActionPerformed);

        Titre.setFont(new java.awt.Font("Fira Sans ExtraBold", 0, 18)); // NOI18N
        Titre.setText("Ajout d'un nouveau Utilisateur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enregistrer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Annuler))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titre)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Titre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Annuler)
                    .addComponent(enregistrer))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        effacerChamps();
        this.dispose();
    }//GEN-LAST:event_AnnulerActionPerformed

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
    try {
        // 1. Instanciation de l'entité
        entity.Users u = new entity.Users();
        
        // 2. Récupération des textes (basé sur tes variables : login, T_pass)
        String loginUser = login.getText().trim();
        String password = T_pass.getText().trim();
        
        if (loginUser.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Le login et le mot de passe sont obligatoires.");
            return;
        }
        
        u.setLogin(loginUser);
        u.setMotDePasse(Security.crypterMotdePasse(password));
        u.setSexe(C_f.isSelected() ? "F" : "M");
        u.setIsAdmin(oui.isSelected());

        dao.UsersDAO daoUser = new dao.UsersDAO();
        CrudResult<Boolean> resi= daoUser.enregistrer(u);
        
        System.out.println();

        // 6. Feedback et fermeture
        javax.swing.JOptionPane.showMessageDialog(this, "Utilisateur ajouté avec succès !");
        this.dispose(); 
        
    } catch (HeadlessException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erreur technique : " + ex.getMessage());
        ex.printStackTrace();
    }
    dispose();
    }//GEN-LAST:event_enregistrerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            UserForm dialog = new UserForm(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.ButtonGroup BG_isadmin;
    private javax.swing.ButtonGroup BG_sexe;
    private javax.swing.JRadioButton C_f;
    private javax.swing.JRadioButton C_m;
    private javax.swing.JLabel L_isAdminn;
    private javax.swing.JLabel L_login;
    private javax.swing.JTextField T_pass;
    private javax.swing.JLabel Titre;
    private javax.swing.JButton enregistrer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField login;
    private javax.swing.JRadioButton non;
    private javax.swing.JRadioButton oui;
    private javax.swing.JLabel passe;
    private javax.swing.JLabel sexe;
    // End of variables declaration//GEN-END:variables
}
